# Generated by Django 6.0.4 on 2026-05-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMeta',
            fields=[
                ('id_campana', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_concesionaria', models.IntegerField()),
                ('sucursal', models.CharField(max_length=100)),
                ('nombre_campana', models.CharField(max_length=500)),
                ('inicio_campana', models.DateField(blank=True, null=True)),
                ('fin_campana', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campanas_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapeoFuenteMeta',
            fields=[
                ('id_fuente', models.CharField(db_column='id_fuente', max_length=120, primary_key=True, serialize=False)),
                ('tipo_fuente', models.CharField(max_length=30)),
                ('id_campana', models.BigIntegerField(blank=True, null=True)),
                ('nombre_campana', models.CharField(blank=True, default='', max_length=500)),
                ('id_anuncio', models.BigIntegerField(blank=True, null=True)),
                ('nombre_anuncio', models.CharField(blank=True, default='', max_length=500)),
                ('id_conjunto', models.BigIntegerField(blank=True, null=True)),
                ('nombre_conjunto', models.CharField(blank=True, default='', max_length=500)),
                ('sucursal', models.CharField(blank=True, default='', max_length=100)),
                ('respuesta_meta', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapeo_fuentes_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('business', models.CharField(blank=True, default='', max_length=120)),
                ('canal_contacto', models.CharField(blank=True, default='', max_length=120)),
                ('pauta', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(blank=True, default='', max_length=120)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('asesor_digital', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_ventas', models.CharField(blank=True, default='', max_length=200)),
                ('comentarios', models.TextField(blank=True, default='', max_length=2000)),
                ('primer_contacto_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_contacto_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, default='')),
                ('resumen_actualizado_at', models.DateTimeField(blank=True, null=True)),
                ('resumen_fuente', models.CharField(blank=True, default='', max_length=30)),
                ('ultima_cita_agendada', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='expediente_digital_volvo', to='citas.clientecomercial')),
                ('ultima_cita', models.ForeignKey(blank=True, db_column='id_ultima_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='citas.cita')),
            ],
            options={
                'db_table': 'expediente_digital_volvo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LecturaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=15)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_whatsapp_volvo', to='Digitales.expedientedigital')),
            ],
            options={
                'db_table': 'digitales_lecturas_whatsapp_volvo',
                'managed': True,
                'indexes': [models.Index(fields=['expediente', 'numero_asesor'], name='digitales_l_expedie_5ef66a_idx'), models.Index(fields=['numero_asesor', 'last_read_at'], name='digitales_l_numero__f5c55a_idx')],
                'unique_together': {('expediente', 'numero_asesor')},
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=32)),
                ('numero_asesor', models.CharField(max_length=15)),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('body', models.TextField(blank=True, default='')),
                ('wa_message_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, default='sent', max_length=30)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp_volvo', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'digitales_mensajes_volvo',
                'ordering': ['created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['telefono', 'numero_asesor', 'created_at'], name='digitales_m_telefon_08fb82_idx'), models.Index(fields=['numero_asesor', 'created_at'], name='digitales_m_numero__ab8f25_idx'), models.Index(fields=['wa_message_id'], name='digitales_m_wa_mess_27516d_idx')],
            },
        ),
    ]
