# Generated by Django 6.0.4 on 2026-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='buro_estado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='comprobacion_ingresos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='enganche_monto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='forma_pago',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='plazo_compra',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='presupuesto_mensual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='tipo_cliente',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='uso_vehiculo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
