# Generated by Django 6.0.4 on 2026-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0002_expedientedigital_buro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='numero_asesor',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='status',
            field=models.CharField(blank=True, default='sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='wa_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
