# Generated by Django 6.0.4 on 2026-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0003_alter_mensajewhatsapp_id_and_more'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajewhatsapp',
            options={'managed': True, 'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='mensajewhatsapp',
            name='digitales_m_telefon_08fb82_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensajewhatsapp',
            name='digitales_m_wa_mess_27516d_idx',
        ),
        migrations.RenameIndex(
            model_name='mensajewhatsapp',
            new_name='volvo_msg_line_dt_idx',
            old_name='digitales_m_numero__ab8f25_idx',
        ),
        migrations.AlterField(
            model_name='expedientedigital',
            name='primer_contacto_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedientedigital',
            name='ultimo_contacto_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturawhatsapp',
            name='numero_asesor',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='numero_asesor',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='expedientedigital',
            index=models.Index(fields=['-actualizado'], name='expediente__actuali_2da009_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientedigital',
            index=models.Index(fields=['agencia', 'business'], name='expediente__agencia_e35519_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientedigital',
            index=models.Index(fields=['estado'], name='expediente__estado_4b402d_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['telefono', 'numero_asesor', 'created_at', 'id'], name='volvo_msg_tel_line_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['telefono', 'numero_asesor', '-created_at', '-id'], name='volvo_msg_tel_line_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['wa_message_id', 'numero_asesor'], name='volvo_msg_wa_line_idx'),
        ),
    ]
