# Generated by Django 6.0.4 on 2026-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0004_alter_mensajewhatsapp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='folio_solicitud_credito',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='id_cotizacion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='motivo_descalificacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='solicitud_credito_estado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='vin_estatus_entrega',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='vin_facturado',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterModelTable(
            name='campanameta',
            table='campanas_meta_volvo',
        ),
    ]
