# Generated by Django 6.0.4 on 2026-07-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0005_expedientedigital_folio_solicitud_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIAWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(max_length=15, unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('horarios', models.JSONField(blank=True, default=dict)),
                ('identidad', models.TextField(blank=True, default='')),
                ('precios', models.TextField(blank=True, default='')),
                ('perfilamiento', models.TextField(blank=True, default='')),
                ('limites', models.TextField(blank=True, default='')),
                ('personalidad', models.TextField(blank=True, default='')),
                ('condiciones_fijas', models.TextField(blank=True, default='')),
                ('promociones_eventos', models.TextField(blank=True, default='')),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=120)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'configuracion_ia_whatsapp_volvo',
                'ordering': ['numero_asesor'],
            },
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='cotizacion_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='cotizacion_solicitada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ia_pausada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ia_pausada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ia_pausada_motivo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='motivo_requiere_asesor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='requiere_asesor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CatalogoVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Volvo', max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('ano', models.PositiveSmallIntegerField()),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('precio_lista', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_contado', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_financiado', models.PositiveIntegerField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, default='')),
                ('ficha_tecnica', models.JSONField(blank=True, default=dict)),
                ('url_ficha_tecnica', models.CharField(blank=True, default='', max_length=800)),
                ('imagenes', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('ultima_actualizacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalogo_vehiculos_volvo',
                'ordering': ['marca', 'modelo', 'ano', 'version'],
                'constraints': [models.UniqueConstraint(fields=('marca', 'modelo', 'ano', 'version'), name='uniq_catalogo_volvo_modelo_version')],
            },
        ),
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=15)),
                ('ia_activa', models.BooleanField(default=True)),
                ('ia_pausada', models.BooleanField(default=False)),
                ('motivo_pausa', models.CharField(blank=True, default='', max_length=120)),
                ('estado_conversacion', models.CharField(blank=True, default='sin_iniciar', max_length=50)),
                ('pregunta_pendiente', models.CharField(blank=True, default='', max_length=80)),
                ('pregunta_pendiente_intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultima_intencion', models.CharField(blank=True, default='', max_length=80)),
                ('ultimo_modelo_mencionado', models.CharField(blank=True, default='', max_length=120)),
                ('resumen_conversacion', models.TextField(blank=True, default='')),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia_volvo', to='Digitales.expedientedigital')),
            ],
            options={
                'db_table': 'conversacion_ia_volvo',
                'constraints': [models.UniqueConstraint(fields=('expediente', 'numero_asesor'), name='uniq_conversacion_ia_volvo_exp_linea')],
            },
        ),
    ]
