# Generated by Django 5.2.5 on 2026-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0006_configuracioniawhatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_por',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_respuesta_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
