# Generated by Django 6.0.4 on 2026-05-25 12:43

import checklist_entrega.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEntregaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='Volvo', max_length=120)),
                ('asesor_servicio', models.CharField(blank=True, default='', max_length=200)),
                ('tecnico_responsable', models.CharField(blank=True, default='', max_length=200)),
                ('placas', models.CharField(blank=True, default='', max_length=40)),
                ('vin', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('kilometraje', models.CharField(blank=True, default='', max_length=50)),
                ('orden_servicio', models.CharField(blank=True, default='', max_length=80)),
                ('factura', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_hora_entrega', models.DateTimeField(blank=True, null=True)),
                ('metodo_contacto_preferido', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('correo', 'Correo'), ('llamada', 'Llamada')], default='whatsapp', max_length=30)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('entrega_terminada', models.BooleanField(default=False)),
                ('fecha_terminada', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='checklists_entrega_volvo', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'volvo_checklist_entrega',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaChecklistEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=checklist_entrega.models.evidencia_checklist_entrega_upload_to)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='checklist_entrega.checklistentregavehiculo')),
            ],
            options={
                'db_table': 'volvo_checklist_entrega_evidencias',
                'ordering': ['-creado'],
            },
        ),
    ]
