from django.db import models


class MatrizPresupuesto(models.Model):
    pk = models.CompositePrimaryKey("agencia", "rowid")

    agencia = models.TextField(db_column="Agencia")
    nr_orcamento = models.BigIntegerField(db_column="NrOrcamento")
    cod_entidade = models.BigIntegerField(db_column="CodEntidade", null=True, blank=True)
    nome = models.TextField(db_column="Nome", null=True, blank=True)
    endereco = models.TextField(db_column="Endereco", null=True, blank=True)
    bairro = models.TextField(db_column="Bairro", null=True, blank=True)
    cod_munic = models.BigIntegerField(db_column="CodMunic", null=True, blank=True)
    cep = models.BigIntegerField(db_column="Cep", null=True, blank=True)
    tel_fax1 = models.BigIntegerField(db_column="TelFax1", null=True, blank=True)
    tel_fax2 = models.BigIntegerField(db_column="TelFax2", null=True, blank=True)
    tp_pessoa = models.TextField(db_column="TpPessoa", null=True, blank=True)
    cgc = models.TextField(db_column="CGC", null=True, blank=True)
    rg = models.TextField(db_column="Rg", null=True, blank=True)
    cod_segurad = models.BigIntegerField(db_column="CodSegurad", null=True, blank=True)
    placa_veic = models.TextField(db_column="PlacaVeic", null=True, blank=True)
    chassi = models.TextField(db_column="Chassi", null=True, blank=True)
    km = models.BigIntegerField(db_column="Km", null=True, blank=True)
    cor_veic = models.TextField(db_column="CorVeic", null=True, blank=True)
    cod_modelo = models.TextField(db_column="CodModelo", null=True, blank=True)
    ano_fabr = models.BigIntegerField(db_column="AnoFabr", null=True, blank=True)
    ano_mod = models.BigIntegerField(db_column="AnoMod", null=True, blank=True)
    vr_produtos = models.FloatField(db_column="VrProdutos", null=True, blank=True)
    vr_mdo_pub = models.FloatField(db_column="VrMDO_Pub", null=True, blank=True)
    dt_emissao = models.TextField(db_column="DtEmissao", null=True, blank=True)
    hr_emissao = models.BigIntegerField(db_column="HrEmissao", null=True, blank=True)
    dt_validade = models.TextField(db_column="DtValidade", null=True, blank=True)
    dt_aprov = models.TextField(db_column="DtAprov", null=True, blank=True)
    sit = models.TextField(db_column="Sit", null=True, blank=True)
    nr_prisma = models.BigIntegerField(db_column="NrPrisma", null=True, blank=True)
    cor_prisma = models.TextField(db_column="CorPrisma", null=True, blank=True)
    cod_func = models.BigIntegerField(db_column="CodFunc", null=True, blank=True)
    comentario = models.TextField(db_column="Comentario", null=True, blank=True)
    nr_apolice = models.TextField(db_column="NrApolice", null=True, blank=True)
    desc_pcs = models.FloatField(db_column="DescPcs", null=True, blank=True)
    vr_desc_pcs = models.FloatField(db_column="VrDescPcs", null=True, blank=True)
    desc_serv = models.FloatField(db_column="DescServ", null=True, blank=True)
    vr_desc_serv = models.FloatField(db_column="VrDescServ", null=True, blank=True)
    nr_at_ped = models.BigIntegerField(db_column="NrAtPed", null=True, blank=True)
    tp_entrega = models.BigIntegerField(db_column="TpEntrega", null=True, blank=True)
    dest_ped = models.TextField(db_column="DestPed", null=True, blank=True)
    tp_preco = models.TextField(db_column="TpPreco", null=True, blank=True)
    impr_cod_pcs = models.TextField(db_column="ImprCodPcs", null=True, blank=True)
    area_orcam = models.TextField(db_column="AreaOrcam", null=True, blank=True)
    cod_contacto = models.FloatField(db_column="CodContacto", null=True, blank=True)
    cod_pacote = models.TextField(db_column="CodPacote", null=True, blank=True)
    sinistro = models.TextField(db_column="Sinistro", null=True, blank=True)
    ajustador = models.TextField(db_column="Ajustador", null=True, blank=True)
    orcam_dyp = models.TextField(db_column="OrcamDyP", null=True, blank=True)
    pres_elsa_pro = models.TextField(db_column="PresElsaPro", null=True, blank=True)
    pres_elsa_aut = models.TextField(db_column="PresElsaAut", null=True, blank=True)
    nr_atend = models.BigIntegerField(db_column="NrAtend", null=True, blank=True)
    vr_adicionais = models.FloatField(db_column="VrAdicionais", null=True, blank=True)
    nr_remision = models.BigIntegerField(db_column="NrRemision", null=True, blank=True)
    nr_convenio = models.BigIntegerField(db_column="NrConvenio", null=True, blank=True)
    asegurado = models.TextField(db_column="Asegurado", null=True, blank=True)
    taller = models.TextField(db_column="Taller", null=True, blank=True)
    nr_vale = models.TextField(db_column="NrVale", null=True, blank=True)
    nr_orden_cpa = models.TextField(db_column="NrOrdenCpa", null=True, blank=True)
    cod_empresa = models.BigIntegerField(db_column="Cod_Empresa", null=True, blank=True)
    cod_filial = models.BigIntegerField(db_column="Cod_Filial", null=True, blank=True)
    rowid = models.BigIntegerField(db_column="rowid__")

    class Meta:
        managed = False
        db_table = "Matriz_Presupuestos"


class MatrizPresupuestoRef(models.Model):
    pk = models.CompositePrimaryKey("agencia", "rowid")

    agencia = models.TextField(db_column="Agencia")
    nr_orcamento = models.BigIntegerField(db_column="NrOrcamento")
    nm_prod = models.TextField(db_column="NmProd", null=True, blank=True)
    cod_prod = models.TextField(db_column="CodProd", null=True, blank=True)
    qt_prod = models.FloatField(db_column="QtProd", null=True, blank=True)
    preco_pc = models.FloatField(db_column="PrecoPc", null=True, blank=True)
    desc_pc = models.FloatField(db_column="DescPc", null=True, blank=True)
    vr_desc_pc = models.FloatField(db_column="VrDescPc", null=True, blank=True)
    vr_liq_pc = models.FloatField(db_column="VrLiqPc", null=True, blank=True)
    vr_casco = models.FloatField(db_column="VrCasco", null=True, blank=True)
    hr_creacion = models.FloatField(db_column="HrCreacion", null=True, blank=True)
    dn_stock = models.FloatField(db_column="DNStock", null=True, blank=True)
    dn_media_vta = models.FloatField(db_column="DNMediaVta", null=True, blank=True)
    dn_ct_solicitada = models.FloatField(db_column="DNCtSolicitada", null=True, blank=True)
    filler05 = models.FloatField(db_column="Filler05", null=True, blank=True)
    filler06 = models.FloatField(db_column="Filler06", null=True, blank=True)
    filler07 = models.FloatField(db_column="Filler07", null=True, blank=True)
    filler08 = models.FloatField(db_column="Filler08", null=True, blank=True)
    filler09 = models.FloatField(db_column="Filler09", null=True, blank=True)
    filler10 = models.FloatField(db_column="Filler10", null=True, blank=True)
    selec = models.TextField(db_column="Selec", null=True, blank=True)
    id_casco = models.TextField(db_column="IdCasco", null=True, blank=True)
    impr_desc = models.TextField(db_column="ImprDesc", null=True, blank=True)
    filler12 = models.TextField(db_column="Filler12", null=True, blank=True)
    filler13 = models.TextField(db_column="Filler13", null=True, blank=True)
    filler14 = models.TextField(db_column="Filler14", null=True, blank=True)
    filler15 = models.TextField(db_column="Filler15", null=True, blank=True)
    filler16 = models.TextField(db_column="Filler16", null=True, blank=True)
    cod_pacote = models.TextField(db_column="CodPacote", null=True, blank=True)
    filler17 = models.TextField(db_column="Filler17", null=True, blank=True)
    coment_ref = models.TextField(db_column="ComentRef", null=True, blank=True)
    dt_creacion = models.TextField(db_column="DtCreacion", null=True, blank=True)
    filler20 = models.TextField(db_column="Filler20", null=True, blank=True)
    rowid = models.BigIntegerField(db_column="rowid__")

    class Meta:
        managed = False
        db_table = "Matriz_PresupuestosRef"