# Generated by Django 6.0.4 on 2026-05-25 12:43

import checklist_general.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistGeneralCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='Volvo', max_length=120)),
                ('asesor_servicio', models.CharField(blank=True, default='', max_length=200)),
                ('tecnico_inspector', models.CharField(blank=True, default='', max_length=200)),
                ('gerente_servicio', models.CharField(blank=True, default='', max_length=200)),
                ('pst', models.CharField(blank=True, default='', max_length=200)),
                ('placas', models.CharField(blank=True, default='', max_length=40)),
                ('vin', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('kilometraje', models.CharField(blank=True, default='', max_length=50)),
                ('orden_servicio', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_hora_revision', models.DateTimeField(blank=True, null=True)),
                ('requiere_prueba_manejo', models.BooleanField(default=True)),
                ('fecha_prueba', models.DateField(blank=True, null=True)),
                ('hora_prueba', models.TimeField(blank=True, null=True)),
                ('kilometraje_inicial', models.CharField(blank=True, default='', max_length=50)),
                ('kilometraje_final', models.CharField(blank=True, default='', max_length=50)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('checklist_terminado', models.BooleanField(default=False)),
                ('fecha_terminado', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='checklists_generales_volvo', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'volvo_checklist_general',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaChecklistGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=checklist_general.models.evidencia_checklist_general_upload_to)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(db_column='id_checklist', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='checklist_general.checklistgeneralcalidad')),
            ],
            options={
                'db_table': 'volvo_checklist_general_evidencias',
                'ordering': ['-creado'],
            },
        ),
    ]
