# Generated by Django 6.0.4 on 2026-05-23 11:40

import citas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteComercial',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(db_index=True, max_length=32, unique=True)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes_comerciales_volvo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('tipo_cita', models.CharField(blank=True, default='', max_length=120)),
                ('fuente_prospeccion', models.CharField(blank=True, default='', max_length=120)),
                ('asesor_digital', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('comentarios', models.CharField(blank=True, default='', max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'citas_volvo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('vin', models.CharField(blank=True, default='', max_length=2000)),
                ('modelo_version', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora_entrega', models.DateTimeField(blank=True, null=True)),
                ('entrega_reportada', models.BooleanField(default=False)),
                ('asesor_ventas', models.CharField(blank=True, default='', max_length=200)),
                ('preparada_por', models.CharField(blank=True, default='', max_length=2000)),
                ('id_cliente_sf_nadin', models.CharField(blank=True, default='', max_length=2000)),
                ('id_cliente_sf_dms', models.CharField(blank=True, default='', max_length=2000)),
                ('comentarios', models.CharField(blank=True, default='', max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'entregas_volvo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PruebaManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('num_serie', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('comentarios_cliente', models.CharField(blank=True, default='', max_length=2000)),
                ('folio_salida', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_manejo', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'pruebas_manejo_volvo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaPruebaManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=citas.models.ruta_evidencia_prueba)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=120)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prueba_manejo', models.ForeignKey(db_column='id_prueba_manejo', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='citas.pruebamanejo')),
            ],
            options={
                'db_table': 'evidencias_prueba_manejo_volvo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroPiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('be_back', models.BooleanField(default=False)),
                ('fuente_prospeccion', models.CharField(blank=True, default='', max_length=120)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('folio', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_venta', models.CharField(blank=True, default='', max_length=200)),
                ('estado_ingreso', models.CharField(blank=True, default='', max_length=120)),
                ('comentarios_cliente', models.CharField(blank=True, default='', max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='registros_piso', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'registro_piso_volvo',
                'managed': True,
            },
        ),
    ]
