# Generated by Django 6.0.4 on 2026-05-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraficoPiso',
            fields=[
                ('id_trafico', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('nombre_prospecto', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('telefono', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('asesor_ventas', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('motivo_ingreso', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_persona', models.CharField(blank=True, default='', max_length=40)),
                ('tiempo_compra', models.CharField(blank=True, default='', max_length=80)),
                ('auto_suenos', models.CharField(blank=True, default='', max_length=120)),
                ('deja_auto_cuenta', models.BooleanField(default=False)),
                ('modelo_auto_cuenta', models.CharField(blank=True, default='', max_length=200)),
                ('forma_capitalizacion', models.CharField(blank=True, default='', max_length=120)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('enganche_presupuestado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('mensualidades_presupuestadas', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('comprueba_ingresos', models.BooleanField(default=False)),
                ('forma_comprobar_ingresos', models.CharField(blank=True, default='', max_length=120)),
                ('motivo_compra', models.CharField(blank=True, default='', max_length=120)),
                ('perfil_profesional', models.CharField(blank=True, default='', max_length=120)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cantidad_hijos', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('estado_civil', models.CharField(blank=True, default='', max_length=60)),
                ('pasatiempos', models.JSONField(blank=True, default=list)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traficos_piso_volvo_creados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Tráfico de piso Volvo',
                'verbose_name_plural': 'Tráfico de piso Volvo',
                'db_table': 'trafico_piso_volvo',
                'ordering': ['-id_trafico'],
                'indexes': [models.Index(fields=['telefono'], name='trafico_pis_telefon_2d645b_idx'), models.Index(fields=['asesor_ventas'], name='trafico_pis_asesor__c1105e_idx'), models.Index(fields=['agencia'], name='trafico_pis_agencia_fb47ea_idx'), models.Index(fields=['creado_en'], name='trafico_pis_creado__c2e840_idx')],
            },
        ),
    ]
