# Generated by Django 6.0.4 on 2026-05-23 11:40

import django.db.models.deletion
import recepcion_volvo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionVolvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='Volvo', max_length=120)),
                ('asesor_servicio', models.CharField(blank=True, default='', max_length=200)),
                ('placas', models.CharField(blank=True, default='', max_length=40)),
                ('vin', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('kilometraje', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_hora_recepcion', models.DateTimeField(blank=True, null=True)),
                ('metodo_contacto_preferido', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('correo', 'Correo'), ('llamada', 'Llamada')], default='whatsapp', max_length=30)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('recepcion_terminada', models.BooleanField(default=False)),
                ('fecha_terminada', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_volvo', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'volvo_recepciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaRecepcionVolvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=recepcion_volvo.models.evidencia_recepcion_volvo_upload_to)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(db_column='id_recepcion', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='recepcion_volvo.recepcionvolvo')),
            ],
            options={
                'db_table': 'volvo_recepciones_evidencias',
                'ordering': ['-creado'],
            },
        ),
    ]
